server:
  port: 8081

app:
  resource: 
    id: resource1  
#spring:#  security:#    oauth2:#      resourceserver:#        jwt:#          issuer-uri: 
security:  oauth2:    resource:      token-info-uri: http://localhost:8080/oauth/check_token
#      user-info-uri: dd